---
title: "Untitled"
author: "Andrew Zavala"
date: "2/17/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse); library(rio); library(TSA); library(janitor); library(broom); library(lmSupport); library(brms); library(reshape2)
```

```{r}
pilot <- list.files("pilot")
frohlich_data <- NULL

for (i in seq_along(pilot)) {
  temp <- import(paste0("pilot/",pilot[i]))
  frohlich_data <- rbind(frohlich_data, temp)
}

frohlich_data <- frohlich_data %>%
  filter(Trial_Recycled_ == FALSE) %>%
  select(c(Session_Name_, probe_delay, entrainment_type, DURATION, STARTING_ANGLE, MOUSE_ANGLE)) %>%
  mutate(probe_delay = probe_delay*16.6666)

frohlich_data$MOUSE_ANGLE <- ifelse(frohlich_data$MOUSE_ANGLE > 0, frohlich_data$MOUSE_ANGLE, frohlich_data$MOUSE_ANGLE + 360)

frohlich_data <- frohlich_data %>%
  mutate(illusion = MOUSE_ANGLE - STARTING_ANGLE)

frohlich_data <- frohlich_data %>%
  filter(illusion > -50 & illusion < 50)

```

# Graph biases by phase

```{r}

frohlich_data %>%
  #filter(Session_Name_ == "scott") %>%
ggplot(aes(STARTING_ANGLE, illusion)) +
  geom_jitter() +
  geom_smooth(method = "loess", span = .25) +
  facet_wrap(~Session_Name_) +
  theme_minimal() +
  ylab("Illusion Effect (˚)") +
  xlab("Starting Angle of Motion (˚)")

```

# Graph biases by duration

```{r}

frohlich_data %>%
  #filter(Session_Name_ == "claudia") %>%
ggplot(aes(DURATION, illusion)) +
  geom_jitter() +
  geom_smooth(method = "loess") +
  facet_wrap(~Session_Name_) +
  theme_minimal() +
  ylab("Illusion Effect (˚)") +
  xlab("Duration (refreshes)")

# Test duration as a significant predictor

duration_model_0 <- lm(illusion ~ probe_delay,
                       data = frohlich_data)
duration_model_1 <- lm(illusion ~ probe_delay + DURATION,
                       data = frohlich_data)

summary(duration_model_0)
summary(duration_model_1)
```

# Plot illusion data by probe delay

```{r}
frohlich_data %>%
  #filter(Session_Name_ == "claudia") %>%
ggplot(aes(probe_delay, illusion, group = as.factor(entrainment_type), color = as.factor(entrainment_type))) +
  geom_jitter() +
  geom_smooth(method = "loess") +
  facet_grid(entrainment_type ~ Session_Name_) +
  theme_minimal() +
  ylab("Illusion Effect (˚)") +
  xlab("Probe Delay (ms)")

```

# Makin models - get Sara's help

```{r}

claudia_model <- frohlich_data %>%
  filter(Session_Name_ == "claudia") %>%
  lm(illusion ~ probe_delay + as.factor(entrainment_type) + STARTING_ANGLE,
     data = .)

scott_model <- frohlich_data %>%
  filter(Session_Name_ == "scott") %>%
  lm(illusion ~ probe_delay + as.factor(entrainment_type) + STARTING_ANGLE,
     data = .)

ernie_model <- frohlich_data %>%
  filter(Session_Name_ == "ernie") %>%
  lm(illusion ~ probe_delay + as.factor(entrainment_type) + STARTING_ANGLE,
     data = .)

summary(claudia_model)
summary(scott_model)
summary(ernie_model)



```

# tryin stuff

```{r}
library(tidy)
new_object <- frohlich_data %>%
  group_by(Session_Name_) %>%
  arrange(STARTING_ANGLE) %>%
  nest() %>%
  mutate(spec = map(data, function(x) spectrum(x[,"illusion"]))) %>%
  mutate(per = map(spec, function(x) 1/x$freq[x$spec == max(x$spec)])) %>%
  mutate(sine_model = map2(data, per, function(x,y) lm(illusion ~ sin(2*pi/y*STARTING_ANGLE) + cos(2*pi/y*STARTING_ANGLE), data = x))) %>%
  mutate(predicted = map(sine_model, predict)) %>%
  mutate(data = map2(data, predicted, cbind)) %>%
  mutate(data = map(data, function(x) x %>%
                      rename("predicted" = ".y[[1L]]"))) %>%
  mutate(plot = map(data, function(x)
    x %>% ggplot(aes(x = STARTING_ANGLE, y = illusion)) + 
      geom_point() + geom_smooth(se=F) + geom_line(aes(y=predicted), color = "red")))

augmented = new_object %>%
  mutate(resid = map(sine_model, resid)) %>%
  mutate(data = map2(data, resid, cbind)) %>%
  select(Session_Name_, data) %>%
  mutate(data = map(data, function(x) x %>%
                      rename("residual" = ".y[[1L]]"))) %>%
  unnest(cols = c(data))

psych::describe(frohlich_data, fast = T)
```





# Loess fit of biases

```{r}

phase_bias <- predict(loess(STARTING_ANGLE ~ illusion,
                      data = frohlich_data, span = .3),
                      se = TRUE)

span <- seq(0, 1, 0.05)
residuals <- NULL

for (i in seq_along(span)) {
  temp_model <- predict(loess(STARTING_ANGLE ~ illusion,
                      data = frohlich_data, span = i),
                      se = TRUE)
  residuals[i] <- temp_model$residual.scale
}

melt(span, residuals)


```









